import sys
sys.path.append(r'D:/BTECH/All years/4-1/Project/Academic_AI')
from models.data_manager import DataManager
DataManager.refresh()
subjects = DataManager.get('subjects')
qb = DataManager.get('question_bank')
marks = DataManager.get('marks')
cos = DataManager.get('co')
co_po = DataManager.get('co_po')
print('Subjects sample for SUB004:')
print(subjects[subjects['SubjectID'].astype(str).str.contains('004')])
print('\nQuestion bank for SUB004:')
print(qb[qb['SubjectID'].astype(str).str.contains('004')])
print('\nMarks for SUB004:')
print(marks[marks['SubjectID'].astype(str).str.contains('004')].head())
print('\nCOs for SUB004:')
print(cos[cos['SubjectID'].astype(str).str.contains('004')])
print('\nCO_PO mapping for SUB004:')
print(co_po[co_po['SubjectID'].astype(str).str.contains('004')])
